### ISSUE TITLE
Outlook-Add-in-SSO-NAA New Outlook acquireTokenPopup Failure

### ISSUE THREAD

**Issue by johnw86** [OfficeDev/Office-Add-in-samples#1079]
**URL of sample**

[https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO-NAA]

**acquireTokenPopup in New Outlook**

Running the sample code in both office.outlook.com and classic Outlook on windows the flow works correctly. Silent request intitially fails and the code falls back to displaying the tokenPopup requesting the user to grant access. This flow though does not work on New Outlook with an error in the console.

Unable to acquire token via popup: ServerError: native_executor_error

**To Reproduce**

1. Follow instructions to run the sample (manifest.xml)
2. Attempt to use the Get user data button in the sideloaded add-in
3. See that the initial silent attempt fails due to InteractionRequiredAuthError
4. See that the fallback to acquireTokenPopup throws a unhandled error

**Expected behavior**

I would expect the popup to display as it does in classic outlook and outlook web.

**Screenshots**

**New outlook**
<img width="326" height="1023" alt="Image" src="https://github.com/user-attachments/assets/4af52c01-94b2-4cf3-bba2-925ec5287f63" />

**Classic outlook**
<img width="904" height="756" alt="Image" src="https://github.com/user-attachments/assets/6dd658f6-ad0b-4df7-a5b4-2aee6fff8fe3" />

**Environment**
- Platform: PC desktop
- Host: Outlook
- Microsoft Outlook Version: 1.2025.1209.500
- Client Version: 20251212003.10
- WebView2 Version: 143.0.3650.96
- Operating System: Win11

**Comment by davidchesnut** [comment]
@johnw86 and @acoops-lxb looks like this should be fixed now. Can you try again and confirm if resolved for you? Thanks!

**Comment by johnw86** [comment]
Just pulled the latest samples master branch, ran npm install and re-ran the sample and still seeing the same error? Any particular code change I should be looking out for?

@davidchesnut

**Comment by acoops-lxb** [comment]
@davidchesnut Our implementation started working without changes shortly (hours) after my original comment here. Possibly our issue was different and just transient. It is still working without changes presently.

Thanks for the follow-up.
